Fix TSNE page wording issues
responsible-ai-collaborative/aiid pull request #1044
Opened 2022-09-01 16:04 UTC by lmcnulty

Per #1020

2022-09-02 16:47 UTC, cesarvarela requested changes
Does this need updates to the Spanish translations?

2022-09-02 16:47 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/TsneVisualization.js
> +              <Trans>Color by incident classifications from taxonomies</Trans>
Colores basados en la clasificación de los incidentes por su taxonomía

2022-09-02 16:47 UTC, cesarvarela commented on site/gatsby-site/src/templates/tsneVisualizationPage.js
> +          The visualization below shows incidents closer together when a{' '}
La siguiente visualización muestra los incidentes en proximidad proporcional a la similitud semántica de sus textos, identificados a través de <1>nuestro sistema de procesamiento de lenguaje natural</1>

2022-09-02 22:23 UTC, lmcnulty commented
@cesarvarela I've added the changes to the translation. I also noticed that the title was in a `t()` but had no translation. I took a guess and added `"Spatial Visualization": "Visualización espacial"`, but let me know if that's not right.

2022-09-05 17:58 UTC, cesarvarela approved these changes

2022-09-05 17:58 UTC, merged