Feature/login btns
responsible-ai-collaborative/aiid pull request #1108
Opened 2022-09-16 18:42 UTC by clari182

2022-09-20 00:05 UTC, cesarvarela requested changes
Looks good. mergeable after fixing the typo :D

2022-09-20 00:05 UTC, cesarvarela commented on site/gatsby-site/src/components/loginSignup/index.js
> +const LoginSinup = ({ className = '', logoutClassName = '', loginClassName = '' }) => {
typo

2022-09-20 00:05 UTC, cesarvarela commented on site/gatsby-site/src/components/sidebar/index.js
> +import LoginSinup from 'components/loginSignup';
:D

2022-09-20 00:05 UTC, cesarvarela commented on site/gatsby-site/src/components/sidebar/index.js
> +        <LoginSinup
:D

2022-09-20 00:05 UTC, cesarvarela commented on site/gatsby-site/src/components/ui/Header.js
> +import LoginSinup from 'components/loginSignup';
:D

2022-09-20 00:05 UTC, cesarvarela commented on site/gatsby-site/src/components/ui/Header.js
> +                <LoginSinup
:D

2022-09-20 20:36 UTC, clari182 commented
@cesarvarela typo fixed.
I retriggered the deploy and it's all green now: https://app.netlify.com/sites/staging-aiid/deploys/632a1d5df7d1e70f83981fc3
Looks like Github doesn't update the latest deploy preview if it's retriggered from Netlify

2022-09-27 21:12 UTC, clari182 commented
Closing this. Duplicate of #1163

2022-09-27 21:12 UTC, closed without merging