Query tsne statically, add legend
responsible-ai-collaborative/aiid pull request #1206
Opened 2022-10-04 21:06 UTC by lmcnulty

2022-10-07 19:06 UTC, cesarvarela requested changes

2022-10-07 19:06 UTC, cesarvarela commented on site/gatsby-site/i18n/locales/es/translation.json
> +  "The spatial view above shows each incident in the database as a plot point containing its incident ID number. Incidents are positioned so that those with similar report texts fall closer together.
Instead of having such a large key please use something like `tsneDescription`, to prevent translation files from getting too big.

2022-10-07 19:06 UTC, cesarvarela commented on site/gatsby-site/i18n/locales/es/translation.json
> +  "The spatial view above shows each incident in the database as a plot point containing its incident ID number. Incidents are positioned so that those with similar report texts fall closer together.
```
La vista espacial anterior muestra cada incidente en la base de datos como un punto que contiene su número de incidente. Los incidentes se colocan de modo que aquellos con textos similares estén más cerca unos de otros. Por ejemplo, los incidentes relacionados con vehículos autónomos forman un grupo compacto. Determinamos la similitud de los incidentes mediante un sistema de procesamiento de lenguaje natural, sobre el que puede obtener más información en <1>nuestra publicación de blog sobre su implementación</1>.
```

2022-10-13 20:20 UTC, cesarvarela approved these changes
Functional review:
- I expected the legend items to be toggleable, like in the taxonomy pie charts, which you can turn on/off
- using the trackpad to resize is not very fluid, d3 has a couple of helpers that make this smoother (you can test this in the location visualization), but this is something to fix in the future, if ever.

Let me know what you think about the toggleable legend, and I'll merge it afterward.

2022-10-14 14:51 UTC, lmcnulty commented
@cesarvarela The legend now allows toggling categories. Zooming is smoother with some points hidden, but it is worth thinking about how we can improve it in the general case.

https://user-images.githubusercontent.com/25443411/195873343-be2714ac-be63-42f8-8c51-b4a11008d94f.mp4

2022-10-14 20:59 UTC, merged