Feature/collapsable menu
responsible-ai-collaborative/aiid pull request #1313
Opened 2022-10-25 15:44 UTC by clari182

2022-11-03 19:02 UTC, cesarvarela reviewed
Doesn't seem like you need a context since you are using the state in only one place or am I missing something 🤔

2022-11-03 19:04 UTC, cesarvarela commented on site/gatsby-site/src/components/LayoutHideSidebar.js
> -import React, { useState } from 'react';
Why not delete this file altogether?

2022-11-07 16:11 UTC, clari182 commented
Thanks @lmcnulty !! I'll work on your comments

2022-11-09 19:06 UTC, clari182 commented
@lmcnulty ready for another review. I went with the orange arrow at the top that replaces the discover and submit buttons. However I didn't place it between the two when the menu is open because it felt a little strange IMO. Let me know what you think. I also tackled the rest of your comments.

2022-11-09 22:04 UTC, lmcnulty commented
> However I didn't place it between the two when the menu is open because it felt a little strange IMO

I get what you mean, but I find the collapse button floating outside of the sidebar a bit weird as well. What if we made a notch for it to go in? I find This would have been hard to explain so I made a [PR](https://github.com/responsible-ai-collaborative/aiid/pull/1366) for it, although it seems not to be building right now.

<img src="https://user-images.githubusercontent.com/25443411/200950196-6db1cf95-3b2b-4c1f-97a0-945c4d6dc1e1.png"/>

I also made the sidebar no longer sticky, because the bottom was still inaccessible when the screen wasn't tall enough to fit it. Other than that everything looked good.

2022-11-09 22:24 UTC, smcgregor commented
Hot take: I don't think I would connect the open/close button to opening and closing the side menu if it is in the middle of the Discover/Submit buttons.

2022-11-09 22:25 UTC, clari182 commented
Got it! Thanks @lmcnulty I'll include those changes on my PR

2022-11-10 18:15 UTC, lmcnulty commented
> Hot take: I don't think I would connect the open/close button to opening and closing the side menu if it is in the middle of the Discover/Submit buttons.

I agree that it's not immediately obvious that the button in the middle will collapse the sidebar, but I think that it adds more visual interest and that the functionality will become apparent once the arrow flips around when the user visits a page that starts out collapsed. And since being able to manually collapse the sidebar is not necessary to use any functionality of the site, I think that's ok.

Some other options:

1. Put it inset in the bottom corner:
   ![image](https://user-images.githubusercontent.com/25443411/201173155-3cd67f4d-7162-4b32-ac36-fb024c7cf0a0.png)

2. Put it inset in the middle, and maker smaller / less prominent:
   ![image](https://user-images.githubusercontent.com/25443411/201173588-2882add5-6ae4-40e7-8ea0-74fefef0313d.png)


3. Set `cursor: col-resize` when the cursor approaches the edge of the sidebar and allow manually resizing it, like in Slack:

   ![image](https://user-images.githubusercontent.com/25443411/201172180-78f89de3-f02b-4337-899d-350e62c1172d.png)

   Maybe this could also include a narrow handle to communicate that the edge can be grabbed.

2022-11-10 19:08 UTC, cesarvarela reviewed
Not sure if this is ready for review but received a notification so:

Looks like when collapsed there is an option for Discover but not on for Submit.

This seems broken:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/1172479/201183582-04ed9667-b2df-4373-8c03-8707f0589b8f.png">


Maybe use overflow hidden when expanding the menu so you don't see all the cramped-up letters while the expand animation runs?

2022-11-15 18:19 UTC, clari182 commented
@lmcnulty I went with a solution that I think fits with what you were pointing out and what Sean was.
The collapse button is an orange arrow that replaces the Discover/Submit btns when collapsed. Ready for another round of review!
@cesarvarela can you shoot a video of what is happening? I tried in Safari, Chrome and Firefox to reproduce it but no luck. Thanks!

2022-11-15 20:29 UTC, cesarvarela commented
@clari182 happens when you click on the discover menu item (not the big button)

2022-11-15 22:35 UTC, lmcnulty commented
Maybe we could put the button at the bottom and make the icons slide up. E.g.


https://user-images.githubusercontent.com/25443411/202039347-4071e438-540d-4395-bc94-aedbbb652dc9.mp4

Another draft pr: #1387.

2022-11-16 20:48 UTC, clari182 commented
@lmcnulty I moved the arrow down, let me know what you think.
@cesarvarela fixed the discover issue

2022-11-17 18:08 UTC, lmcnulty commented
We still need to do something about the case where the screen is not large enough to fit all the sidebar icons. Currently they're not always possible to reach, and with the collapse arrow at the bottom, it sometimes overlaps.

https://user-images.githubusercontent.com/25443411/202521253-1f57c7a3-c10a-4705-b133-e0e3311beea1.mp4

I'm going to try to come up with a solution on my branch, if that's ok.

2022-11-18 17:18 UTC, clari182 commented
@lmcnulty sounds good Luna. Maybe we can remove the sticky for smaller screen sizes. I think you had already worked on this previously in another branch. I'll put this on hold if you want to take the small screen issue and then incorporate it into this PR.

2022-11-23 19:07 UTC, cesarvarela requested changes
The padding on the left is smaller than on the right. Not sure if it is intentional or not:

![image](https://user-images.githubusercontent.com/1172479/203627096-abd16add-3af2-48a3-8d97-6e84eb7b4383.png)


The tooltip text getting wrapped look funny:

![image](https://user-images.githubusercontent.com/1172479/203626890-1e55c26e-7c1a-4496-8914-8a56e96f1c09.png)

When loading the discover app, the spinner, and some UI components get shifted to the left and then to the center after loading:

![image](https://user-images.githubusercontent.com/1172479/203627501-68137a95-cae0-4bfa-a57d-5559df4b0c75.png)

2022-11-28 18:01 UTC, clari182 commented
@cesarvarela I fixed the 3 changes you requested

2022-12-12 22:58 UTC, cesarvarela commented
What's the "official" one? this or #1387

2022-12-14 17:00 UTC, cesarvarela reviewed
What's the "official" one? this or https://github.com/responsible-ai-collaborative/aiid/pull/1387

2022-12-14 18:36 UTC, clari182 commented
@cesarvarela I think at this point it's best to continue with #1387
Looks better IMO and Luna continued based of my initial work

2022-12-14 19:36 UTC, closed without merging