Subscribe to Entity new incidents
responsible-ai-collaborative/aiid pull request #1350
Opened 2022-11-07 20:50 UTC by pdcp1

Part of issue #1299

<img width="1158" alt="Screen Shot 2022-11-07 at 17 49 24" src="https://user-images.githubusercontent.com/6564809/200412561-1ffc9ec4-7bad-4b3d-8942-e471b8bdad86.png">

2022-11-11 18:28 UTC, cesarvarela commented
Preview link for this?

2022-11-11 20:49 UTC, pdcp1 commented
> Preview link for this?

@cesarvarela https://deploy-preview-12--pablocosta-staging.netlify.app

2022-11-14 17:50 UTC, cesarvarela requested changes
I think that this button should reflect notification status and allow you to toggle on/off:
![image](https://user-images.githubusercontent.com/1172479/201727844-e6f9db5c-d529-408e-a4b0-3b65cbd6750f.png) 🤔

2022-11-14 17:50 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/entity.cy.js
> +  it('Should subscribe to new Entity incidents (authenticated user)', () => {
Tests that use the `login` method must use `maybeIt`

2022-11-14 17:50 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/entity.cy.js
> +    cy.wait(1000);
This will be flaky on CI 🤔

2022-11-14 19:05 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/entity.cy.js
> +    cy.wait(1000);
Removed

2022-11-14 23:22 UTC, pdcp1 commented
@cesarvarela I changed the button behavior to display the subscription status. Please review.
- If the user is subscribed to the Entity:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/6564809/201788314-e5348814-f667-4afb-b10d-668a6fe0b779.png">

- if the user is not subscribed to the Entity:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/6564809/201788414-5bbfc351-0b61-4d42-ad47-b9abe574afae.png">

2022-11-15 20:46 UTC, cesarvarela approved these changes

2022-11-15 20:47 UTC, merged