Entity Subscription Button Style
responsible-ai-collaborative/aiid pull request #1425
Opened 2022-11-29 22:34 UTC by lmcnulty

2023-01-06 23:10 UTC, smcgregor commented
I agree the giant button is not a good look, but the way it displays now (at least on wider screens) feels cluttered to me without good visual separation. The encapsulation of the button made it a bit more visually appealing/separated and the white space between the header content and the first body content is a bit weird.

One idea: move the button right by the entity name, make it a bit less salient, and change the wording to just "Subscribe" or "Notify".

2023-03-13 22:35 UTC, lmcnulty commented
I like "subscribe," but I think that would confusing given that it's the same as the login button. "Notify" doesn't really work on its own -- it's not clear what one is being notified of. I think "follow" plus a tooltip works:

![image](https://user-images.githubusercontent.com/25443411/224847330-aef48a90-0921-48a9-a267-cd4982f39cb4.png)

![image](https://user-images.githubusercontent.com/25443411/224847647-8acd503d-f140-4ad7-aa10-d7fc3497bebe.png)

2023-03-14 21:11 UTC, cesarvarela requested changes

2023-03-14 21:13 UTC, cesarvarela commented
And please fix conflicts!

2023-03-18 20:27 UTC, cesarvarela approved these changes

2023-03-18 20:27 UTC, merged