Fix form issues
responsible-ai-collaborative/aiid pull request #1438
Opened 2022-11-30 21:53 UTC by lmcnulty

Resolves #1406, #1407, #1429, #1430, and 1266 (superceding #1322).

2022-12-08 21:28 UTC, cesarvarela requested changes

2022-12-08 21:28 UTC, cesarvarela commented on site/realm/functions/promoteSubmissionToReport.js
> +        title: submission.incident_title || submission.title,
Please update the test associated with this file.

2022-12-14 16:56 UTC, cesarvarela commented
@lmcnulty please merge staging.

2022-12-15 19:15 UTC, cesarvarela requested changes

2022-12-15 19:15 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/incidents.cy.js
> +    cy.wait(10000);
This wait should be instead a `timeout` in the `cy.get` that queries the toast below.

2022-12-15 19:15 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/incidents.cy.js
> +    cy.wait(10000);
Try using `cy.waitForStableDom` instead.

2022-12-15 19:15 UTC, cesarvarela commented on site/gatsby-site/src/components/incidents/IncidentForm.js
> +    .matches(/^.{3,}$/, {
No need to change it, but there is `min` and `max` available.

2022-12-15 21:15 UTC, lmcnulty commented on site/gatsby-site/cypress/e2e/integration/incidents.cy.js
> +    cy.wait(10000);
Whoops, those were just there so I could inspect what was going on. Removed.

2022-12-21 16:55 UTC, smcgregor commented
@lmcnulty when you are back in, please ping me on this one so we can get it into production. @LKchemposer is blocked on a few items here.

2022-12-22 17:28 UTC, lmcnulty commented
@smcgregor I think this one's ready as it is. Merging staging to make sure the tests still pass.

2022-12-22 23:14 UTC, merged