Feature/discover incident reports
responsible-ai-collaborative/aiid pull request #1504
Opened 2022-12-19 16:40 UTC by clari182

2023-01-18 18:40 UTC, cesarvarela requested changes

2023-01-18 18:40 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/discover.cy.js
> +  it.only('Should display incidents instead of reports when selection Incidents view', () => {
Leftover `it.only`

2023-01-27 14:34 UTC, clari182 commented
Hey @cesarvarela, ready for another review. The preview link is: https://deploy-preview-5--clarayoudale-staging.netlify.app/

2023-01-27 21:12 UTC, cesarvarela approved these changes

2023-01-27 21:13 UTC, merged