Fix navigation tests
responsible-ai-collaborative/aiid pull request #1507
Opened 2022-12-22 16:58 UTC by clari182

- closes #1493

2023-02-13 19:44 UTC, cesarvarela requested changes
This removes de `describe` and skips all test anyway 🤔

2023-02-15 19:15 UTC, clari182 commented
@cesarvarela done!

2023-02-22 22:23 UTC, cesarvarela requested changes

2023-02-22 22:23 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/navigation.cy.js
> +it('Check menu links work (English)', () => {
I wonder what the consequences of missing a `describe` call are, but I would add it for the sake of consistency.

2023-03-10 00:30 UTC, merged