typo: "[..] of AISystem" -> "[..] of AI System"
responsible-ai-collaborative/aiid pull request #1592
Opened 2023-02-08 19:29 UTC by kepae

Fix for https://github.com/responsible-ai-collaborative/aiid/issues/1591:
"There should be a space between `AI` and `System` in `Alleged Developer of AISystem`"

Not addressed here because I haven't explored the header/key translation logic fully: there are also differences in the capitalizations in some locales for different pages, which may or may not affect this translation lookup.
e.g.
`site/gatsby-site/i18n/locales/fr/translation.json`: "Alleged Developer of **AI System**"
`site/gatsby-site/i18n/locales/fr/submit.json`: "Alleged developer of **AI system**"

2023-02-10 18:34 UTC, clari182 requested changes
@kepae looks good! However, before I approve, can you update the PR base branch to staging? (instead of master).
Thanks!

2023-02-10 18:36 UTC, smcgregor commented
@clari182 I had the permissions and updated the target branch.

2023-02-10 20:15 UTC, kepae commented
Ah, right, the lesson is stick to staging. Thanks!

2023-02-13 15:00 UTC, clari182 approved these changes

2023-02-13 19:40 UTC, merged