Save sortBy in URL and use that param to sort
responsible-ai-collaborative/aiid pull request #1655
Opened 2023-02-27 14:16 UTC by clari182

- close #1650

2023-02-28 21:18 UTC, pdcp1 requested changes

2023-02-28 21:18 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/discover.cy.js
> +      '?display=details&is_incident_report=true&page=1&sortBy=relevance'
We should add another test to check if the sort selector is set with the value from the URL

2023-03-01 19:55 UTC, clari182 commented
@pdcp1 done!

2023-03-01 19:58 UTC, pdcp1 approved these changes

2023-03-02 17:29 UTC, merged