Improve incident table page performance
responsible-ai-collaborative/aiid pull request #1666
Opened 2023-02-28 22:33 UTC by pdcp1

This closes https://github.com/responsible-ai-collaborative/aiid/issues/1409

2023-03-01 20:01 UTC, cesarvarela requested changes

2023-03-01 20:05 UTC, pdcp1 commented on site/gatsby-site/src/components/incidents/IncidentsTable.js
> +        disableFilters: true,
Actually, we can't filter by entities with this approach since we don't have all the rows' information loaded in memory in order to filter.

2023-03-01 20:22 UTC, pdcp1 commented on site/gatsby-site/src/components/incidents/IncidentsTable.js
> +              <a key={`entity-${v.name}`} href={url} data-cy="cell-entity-link">
done

2023-03-01 20:23 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
> +  maybeIt('Successfully filter and edit incident 112', { retries: { runMode: 4 } }, () => {
As far I understand, if the user and pass are set, the `it` will work in the same way as `maybeIt`

2023-03-02 17:20 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
> +  maybeIt('Successfully filter and edit incident 112', { retries: { runMode: 4 } }, () => {
Yeah but production doesn't have login credentials so this test should've never worked.

2023-03-02 17:21 UTC, cesarvarela commented on site/gatsby-site/src/components/incidents/IncidentsTable.js
> +        disableFilters: true,
@smcgregor @LKchemposer what do you think?

2023-03-02 17:24 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
> +  maybeIt('Successfully filter and edit incident 112', { retries: { runMode: 4 } }, () => {
🤷  weird. Now with the `maybeit` it works

2023-03-02 17:24 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/apps/incidents.cy.js
> +  maybeIt('Successfully filter and edit incident 112', { retries: { runMode: 4 } }, () => {
🤷  weird. Now with the `maybeit` it works

2023-03-02 19:25 UTC, cesarvarela approved these changes

2023-03-02 19:25 UTC, merged