Feature/cite improvements
responsible-ai-collaborative/aiid pull request #1680
Opened 2023-03-02 16:19 UTC by clari182

- closes #1639

2023-03-04 23:55 UTC, smcgregor commented
@clari182 thanks for the checklist/details. My design review below, I have not looked at the implementation yet.

* @Janetbananet and I differ in our preferred orderings. I prefer the description at the top of the page, while she expressed a preference for the tools being higher. If anyone else would like to weigh in on this one, please do so! Otherwise, I'll ask you to move the description back up. In the event the description is lower, then it needs to be in a card or otherwise improved in its display. Going from card to content without a card, then back to card, looks messy. When the description is at the top, it appears more like a subtitle and looks better.
* The big image component very often does not present the image particularly well due to proportion differences. Maybe this needs to have its own issue and we roll it back on this one?
* The big image component shows reports...I think it should likely go after the timeline or at the very least under the `## Incident Reports` section.
* The spinner on page load is distracting. The user will naturally look at the spinner until it resolves and our system response time is long enough for that to be distracting. I don't think we are going to speed up the server response time here, but we can make it so that users don't stare at it. At worst case, I think we should make it so the button is not dynamically checking subscribe status.
* The unevenness on the cards looks a bit messy to me. For example, here there is a dangling line below the image that stops mid sentence while there is still a bunch of whitespace to the right. Ideally, either the content would run to the end of the card or it would never have that last line that goes beyond the image. This may be a new issue rather than something on this PR.
<img width="867" alt="Screen Shot 2023-03-04 at 3 42 24 PM" src="https://user-images.githubusercontent.com/64780/222933664-2ca53308-dc56-40ba-8e62-57196fe6e5de.png">

* The citation info modal has a smaller header than the contents within the modal.
* There is a random line below the BibTek block's copy button that looks like a rendering error.
* There is extra whitespace below the close button on the modal
* The copy buttons both have equal saliency to the close button. I think we typically use buttons without color fill for these sorts of actions.
* Let's add details to "why" we are asking people to use a specific citation format. Something like a context popup or tooltip next to "Suggested Citation Format" indicating, "Citing this specific format will make it possible for the Incident Database to find your research and include it on this page."
<img width="674" alt="Screen Shot 2023-03-04 at 3 47 32 PM" src="https://user-images.githubusercontent.com/64780/222934141-43496b89-a481-44a7-8e0f-71139157ef7c.png">

* It looks like this branch conflicts with `staging` at the moment.

2023-03-06 18:49 UTC, clari182 commented
> @clari182 thanks for the checklist/details. My design review below, I have not looked at the implementation yet.
> 
> * @Janetbananet and I differ in our preferred orderings. I prefer the description at the top of the page, while she expressed a preference for the tools being higher. If anyone else would like to weigh in on this one, please do so! Otherwise, I'll ask you to move the description back up. In the event the description is lower, then it needs to be in a card or otherwise improved in its display. Going from card to content without a card, then back to card, looks messy. When the description is at the top, it appears more like a subtitle and looks better.

**Done: I agree, the description looks better first, without a card and the Tools right below. I think adding one more card for description is not necessary, it's more readable as it is now, at the top.**

> * The big image component very often does not present the image particularly well due to proportion differences. Maybe this needs to have its own issue and we roll it back on this one?

**With this are you referring to the carousel? I changed the carousel now, to use the flowbite one (instead of the bootstrap). I think it looks better. For the sizing of the image I'll take another look but fix in another PR.**

> * The big image component shows reports...I think it should likely go after the timeline or at the very least under the `## Incident Reports` section.

**Done**

> * The spinner on page load is distracting. The user will naturally look at the spinner until it resolves and our system response time is long enough for that to be distracting. I don't think we are going to speed up the server response time here, but we can make it so that users don't stare at it. At worst case, I think we should make it so the button is not dynamically checking subscribe status.

**Done**

> * The unevenness on the cards looks a bit messy to me. For example, here there is a dangling line below the image that stops mid sentence while there is still a bunch of whitespace to the right. Ideally, either the content would run to the end of the card or it would never have that last line that goes beyond the image. This may be a new issue rather than something on this PR.

> 
> <img alt="Screen Shot 2023-03-04 at 3 42 24 PM" width="867" src="https://user-images.githubusercontent.com/64780/222933664-2ca53308-dc56-40ba-8e62-57196fe6e5de.png">
> 

**Maybe the solution here is to display less text when it's collapsed. Since the redesign of this card implied that the text float around the image, it's a little bit tricky to check if a line is not going under the image or not on the collapsed view. This all depends on how the text has been written on the issue. But I'll create a separate issue for this to come up with an improved solution.**

> * The citation info modal has a smaller header than the contents within the modal.

**Done**

> * There is a random line below the BibTek block's copy button that looks like a rendering error.

**Done**

> * There is extra whitespace below the close button on the modal

**Done**

> * The copy buttons both have equal saliency to the close button. I think we typically use buttons without color fill for these sorts of actions.

**Done**

> * Let's add details to "why" we are asking people to use a specific citation format. Something like a context popup or tooltip next to "Suggested Citation Format" indicating, "Citing this specific format will make it possible for the Incident Database to find your research and include it on this page."
> 
> <img alt="Screen Shot 2023-03-04 at 3 47 32 PM" width="674" src="https://user-images.githubusercontent.com/64780/222934141-43496b89-a481-44a7-8e0f-71139157ef7c.png">
> 

**Done**

> * It looks like this branch conflicts with `staging` at the moment.

**Done**

@smcgregor ready for another review

2023-03-06 19:25 UTC, smcgregor commented
It looks like you addressed all my points. I think someone else can do final code review then :shipit:

2023-03-07 19:11 UTC, cesarvarela reviewed
Please ensure the `DEV_SSR` flag is turned on in your gatsby-config file. You should be seeing hydration errors (other than the existing ones)

2023-03-07 19:11 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/ImageCarousel.js
> +    // </div>
looks like a leftover

2023-03-07 19:11 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/NotifyButton.js
> +const { Button, Spinner } = require('flowbite-react');
Why are you using `require` instead of `import` not sure if it makes a difference, but I would try to keep it consistent.

2023-03-07 19:11 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/Tools.js
> +  const { isRole, loading } = useUserContext();
This has a high chance of causing hydration errors, in my experience.

2023-03-07 19:11 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/citationTypes/BibTex.js
> +          <FontAwesomeIcon icon={faCopy} className="fas fa-times" style={{ marginRight: '1ch' }} />
This missing the `titleId` prop causes hydration errors too.

2023-03-07 19:11 UTC, cesarvarela commented on site/gatsby-site/src/components/cite/citationTypes/Citation.js
> +          <FontAwesomeIcon icon={faCopy} className="fas fa-times" style={{ marginRight: '1ch' }} />
ditto

2023-03-10 00:45 UTC, cesarvarela requested changes
This still has the old hydration errors. Please merge staging.

2023-03-14 18:32 UTC, clari182 commented
@cesarvarela ready! Latest [deploy](https://app.netlify.com/sites/staging-aiid/deploys/6410b2e77a30d2026fb39e05) worked
Deploy preview: https://deploy-preview-1680--staging-aiid.netlify.app/

2023-03-14 21:17 UTC, cesarvarela commented
@clari182 please fix conflicts!

2023-03-14 21:18 UTC, cesarvarela reviewed
This makes changes related to a test that failed. I wonder if it is because it is introducing flake 🤔

2023-03-15 14:02 UTC, clari182 commented
Hey @cesarvarela conflicts fixed.
About the test, I tried several times and it hasn't failed for me anymore. But how do you suggest I can do to make sure it doesn't happen again?
Otherwise this is ready for review.

2023-03-15 17:15 UTC, cesarvarela commented
@clari182 please fix conflicts!

2023-03-15 20:07 UTC, clari182 commented
@cesarvarela done!

2023-03-15 20:39 UTC, cesarvarela approved these changes

2023-03-15 21:06 UTC, merged