Fix/login redirect
responsible-ai-collaborative/aiid pull request #1713
Opened 2023-03-08 17:23 UTC by clari182

2023-03-09 19:36 UTC, pdcp1 requested changes
Please add tests to this new redirect feature

2023-03-09 19:36 UTC, pdcp1 commented on site/gatsby-site/src/templates/cite.js
> +            to subscribe
Please fix the translations. They are broken after this change with `{' '}`

Spanish version:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/6564809/224134948-510cf04d-d3a7-460a-8e2b-eb3e9647f956.png">

2023-03-09 19:36 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +            to subscribe
The same here. Please fix the translations. They are broken after this change with `{' '}`

Spanish version:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/6564809/224134948-510cf04d-d3a7-460a-8e2b-eb3e9647f956.png">

2023-03-10 15:32 UTC, pdcp1 requested changes

2023-03-10 15:32 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +            to subscribe
@clari182 Please go to https://deploy-preview-1713--staging-aiid.netlify.app/es/entities/facebook/ and click on `Notificarme de nuevos Incidentes de Facebook` and you will see the toast in English

2023-03-10 15:32 UTC, pdcp1 commented on site/gatsby-site/src/templates/cite.js
> +            to subscribe
@clari182 Please go to https://deploy-preview-1713--staging-aiid.netlify.app/es/cite/421/ and click on `Notificarme de actualizaciones` and you will see the toast in English

2023-03-10 18:48 UTC, pdcp1 approved these changes

2023-03-10 18:48 UTC, pdcp1 commented on site/gatsby-site/src/templates/cite.js
> +            to subscribe
fixed

2023-03-10 21:43 UTC, cesarvarela requested changes
I checked twice, but looks like this is still missing tests?

2023-03-11 19:35 UTC, clari182 commented
@cesarvarela the redirectTo tests were already there in [staging](https://github.com/responsible-ai-collaborative/aiid/blob/400a1febacb7f231fbac4a0d72418f12f1375f7c/site/gatsby-site/cypress/e2e/integration/login.cy.js#L12).
Actually the logic of the redirectTo was already done, what was missing was using it.

2023-03-14 21:08 UTC, cesarvarela approved these changes

2023-03-14 21:08 UTC, merged