Remove styled components from TSNE page
responsible-ai-collaborative/aiid pull request #1761
Opened 2023-03-22 13:48 UTC by clari182

- Helps with #1617

2023-03-22 18:36 UTC, clari182 commented
Sorry @lmcnulty , not ready for review yet! My bad

2023-03-22 19:45 UTC, clari182 commented
Ready for review!

2023-03-23 00:21 UTC, lmcnulty requested changes
![image](https://user-images.githubusercontent.com/25443411/227067494-14a5c719-2ac2-4f3f-97a8-81faff65dc71.png)

When you color in the white background, the bottom of the card image preview is rounded when it should be flat.

2023-03-23 00:21 UTC, lmcnulty commented on site/gatsby-site/src/tailwind.css
> +        @apply block min-h-[15em] w-60 rounded-[0.25rem] shadow-tsne absolute p-4 overflow-hidden;
![image](https://user-images.githubusercontent.com/25443411/227065327-9b6519d9-ad1c-4bc0-aa16-fdd02946e4a3.png)

I think this also needs `bg-white`.

2023-03-23 18:09 UTC, lmcnulty commented
Thanks! Some more things:

When zoomed in heavily, the card offset is weird. Also, the plot point should not turn white when hovered.

<table>
<tr>
<th>This PR</th>
<th>Current</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/25443411/227294701-9159b279-c85e-4bd3-855b-a0bc74bbeac7.png"/></td> 
<td><img src="https://user-images.githubusercontent.com/25443411/227295502-18df13c8-980a-4325-8f16-95ba02eea102.png"/></td>
</tr>
</table>

The plot point opacity should have a transition:

<table>
<tr>
<th>This PR</th>
<th>Current</th>
</tr>
<tr>
<td><video src="https://user-images.githubusercontent.com/25443411/227299637-7b51dc77-28f0-4539-96fe-2891389edcf8.mp4"/></td>

<td><video src="https://user-images.githubusercontent.com/25443411/227298755-9fce6107-dd93-4308-b15f-e5cda15d82d1.mp4"/></td>
</tr>
</table>

The points with classifications should appear above the unclassified ones:

<table>
<tr>
<th>This PR</th>
<th>Current</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/25443411/227302530-ed03bb9c-3522-4f2c-bc52-a253b6d0fe23.png"/></td>
<td><img src="https://user-images.githubusercontent.com/25443411/227302760-6b95b5d5-4071-4436-a6d1-77626ad237a3.png"/></td>
</tr>
</table>

2023-03-24 14:13 UTC, clari182 commented
Ready for another round of review @lmcnulty !

2023-03-24 20:26 UTC, lmcnulty approved these changes

2023-03-24 20:46 UTC, cesarvarela commented
@clari182 please fix conflicts

2023-03-27 14:41 UTC, clari182 commented
Done @cesarvarela !

2023-03-28 20:23 UTC, merged