Feature/image tests
responsible-ai-collaborative/aiid pull request #1844
Opened 2023-04-07 14:49 UTC by clari182

- closes #1833

2023-04-12 15:59 UTC, cesarvarela reviewed
I was thinking more about testing the component in different situations, like when the image loading fails to make sure it is rendering a fallback.

2023-04-12 15:59 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/images/cloudinaryImages.cy.js
> +            it.skip(`Should display a placeholder image if image is failing on page ${path}`, () => {});
I think this line is not necessary.

2023-04-12 15:59 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/images/cloudinaryImages.cy.js
> +                    if (resp.status === 400 || resp.status === 404) {
You should also make sure that the fallback is showing

2023-04-12 15:59 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/images/cloudinaryImages.cy.js
> +    it(`Should not display broken images on page ${path}`, () => {
Please move these tests to the `pages.cy.js`file to save some loading time.

2023-04-17 13:52 UTC, clari182 commented
@cesarvarela ready for another review

2023-04-17 17:46 UTC, cesarvarela requested changes

2023-04-17 17:46 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/pages.cy.js
> +    it(`Should not display broken images on page ${path}`, () => {
Sorry, I wasn't very clear. Please move these tests to the `it` above so we run them all in one visit to reduce loading times (at least until we have more powerful boxes ).

(let's see how flaky this gets)

2023-04-19 22:32 UTC, cesarvarela approved these changes

2023-04-19 22:32 UTC, merged