User Account Enhancements
responsible-ai-collaborative/aiid pull request #1951
Opened 2023-05-02 23:50 UTC by cesarvarela

2023-05-05 14:25 UTC, pdcp1 commented
credentials: `mail@cesarvarela.com:12345678`

2023-05-05 15:29 UTC, pdcp1 requested changes

2023-05-05 18:49 UTC, cesarvarela commented on site/gatsby-site/src/components/users/UserEditModal.js
> +                )}
`subscriber@cesarvarela.com:12345678`

2023-05-05 18:57 UTC, pdcp1 commented on site/gatsby-site/src/components/users/UserEditModal.js
> +                )}
It looks good 👍

2023-05-05 19:08 UTC, cesarvarela commented on site/gatsby-site/src/components/forms/SubmitForm.js
> +          submission.submitters = [`${user.customData.first_name} ${user.customData.last_name}`];
Yup, it is exactly that.

2023-05-05 19:09 UTC, cesarvarela commented on site/gatsby-site/src/components/forms/SubmitForm.js
> +          submission.submitters = [`${user.customData.first_name} ${user.customData.last_name}`];
`submitters` field accomplishes two taks:
- allow anonymous users set a submitter field
- have a name associated to a submission/report when exporting the database (we could fix it with a custom script but it is way more work)

2023-05-05 19:12 UTC, pdcp1 commented on site/gatsby-site/src/components/forms/SubmitForm.js
> +          submission.submitters = [`${user.customData.first_name} ${user.customData.last_name}`];
Got it

2023-05-05 19:13 UTC, pdcp1 approved these changes

2023-05-08 16:28 UTC, cesarvarela commented
@smcgregor if you want to check this out before merging, https://deploy-preview-46--cesarvarela-staging.netlify.app/

`mail@cesarvarela.com:12345678`

2023-05-09 00:53 UTC, smcgregor commented
Looking good in general, but I have questions/comments.

* How would multiple submitters work?
* What happens if I edit the submitter after it is in the review queue?
* The user table is not in the snapshots by design, but I believe this changeset stores user-presented data in the user table. We need a snapshot strategy that is aware of privacy and security concerns here.
* This needs a migration to associate all the historical submissions with the user accounts that submitted them. We can limit this to me, @LKchemposer, @Janetbananet, Danny, and @kateperk at present.
* This text is no longer valid: `Enter your name here. If more than one person contributed to collecting the incident, press “enter” to begin a new item. Alternatively, you can enter "Anonymous" as submitter if you do not want to be attributed in the database. Entries in this field will be added to the public leaderboard.`
* The review form renders twice before it is stable

2023-05-09 20:12 UTC, cesarvarela commented
> How would multiple submitters work?

`submissions` and `reports`  have a `user` field containing the user id of the account logged in.

`submissions` and `reports` have a `submitters` field that contains a list of names `[ 'John Doe', 'Jane Doe']`. The first name of this list comes from the name entered in the associated user account, but it is not enforced in the DB (editing your account details won't update the `submitters` field at the moment). 

> What happens if I edit the submitter after it is in the review queue?

You can change the names in the `submitters` list, but the user account associated with the `submission` can't be modified.

> The user table is not in the snapshots by design, but I believe this changeset stores user-presented data in the user table. We need a snapshot strategy that is aware of privacy and security concerns here.

If we keep the `submitters` field as it is, we don't need to expose the `users` collection.

> This needs a migration to associate all the historical submissions with the user accounts that submitted them. We can limit this to me, @LKchemposer, @Janetbananet, Danny, and @kateperk at present.

I'll need a list of the first and last names, user ids, and emails as they are shown on the user admin table.

> This text is no longer valid: Enter your name here. If more than one person contributed to collecting the incident, press “enter” to begin a new item. Alternatively, you can enter "Anonymous" as submitter if you do not want to be attributed in the database. Entries in this field will be added to the public leaderboard.

Could you help me with that?

> The review form renders twice before it is stable

ok


@smcgregor

2023-05-10 04:12 UTC, smcgregor commented
When the user is logged in: "You are currently logged in so this submission will automatically be associated with your account. If you would like to remain anonymous, please open a private browsing window to submit."

New issues

* `editing your account details won't update the submitters field at the moment`
* `You can change the names in the submitters list, but the user account associated with the submission can't be modified.`: We should discuss this on a new issue. Maybe we auto-complete to user accounts underneath the form? The choices are not trivial.
* This seems reasonable for the short term, but we need a backup strategy now. Maybe we just use MongoDB Atlas's inbuilt tools?
* `I'll need a list of the first and last names, user ids, and emails as they are shown on the user admin table.` Assign me on this one.

2023-05-10 19:05 UTC, cesarvarela commented
> The review form renders twice before it is stable

I don't know what you mean by the review form.

Good to merge this to staging?

@smcgregor

2023-05-10 19:06 UTC, smcgregor commented
Yes.

If go to the submission review page, it will render, then it will update many of the badges.

2023-05-10 20:39 UTC, merged