Remove unused packages and files
responsible-ai-collaborative/aiid pull request #1987
Opened 2023-05-11 18:50 UTC by cesarvarela

2023-05-11 19:46 UTC, pdcp1 requested changes
Please fix conflicts

2023-05-11 19:46 UTC, pdcp1 commented on site/gatsby-site/package.json
>      "@sendgrid/mail": "^7.7.0",
We should remove this `@sendgrid/mail` package as well

2023-05-11 19:46 UTC, pdcp1 commented on site/gatsby-site/netlify.toml
> +    enable = false
What is this `postBuild` step for?

2023-05-11 19:51 UTC, cesarvarela commented on site/gatsby-site/netlify.toml
> +    enable = false
woot that's a leftover

2023-05-11 19:57 UTC, pdcp1 commented
@cesarvarela Do you have a link to do a smoke test to the whole site?

2023-05-12 15:17 UTC, pdcp1 approved these changes
The code looks good to me 👍 
I also did a smoke test on the whole site and it looks good as well

2023-05-15 18:33 UTC, merged