Ask users to fill additional fields after signup
responsible-ai-collaborative/aiid pull request #2007
Opened 2023-05-16 21:26 UTC by cesarvarela

2023-05-19 15:28 UTC, pdcp1 requested changes

2023-05-19 21:43 UTC, cesarvarela commented on site/gatsby-site/src/pages/signup.js
> +    localStorage.setItem('signup', Date.now().toString());
Oh yes I forgot to push the last commit

2023-05-19 21:44 UTC, cesarvarela commented
@pdcp1 please try again

2023-05-23 17:11 UTC, pdcp1 approved these changes

2023-05-23 18:11 UTC, merged