New Report History page
responsible-ai-collaborative/aiid pull request #2221
Opened 2023-08-07 15:20 UTC by pdcp1

2023-08-08 20:14 UTC, cesarvarela reviewed
Looks good. I'll wait for the small issues in #2216 to get addressed and merged to check on this one again.

2023-08-08 20:14 UTC, cesarvarela commented on site/gatsby-site/cypress/e2e/integration/reportHistory.cy.js
> +describe('Incidents', () => {
nit: should say `Reports`

2023-08-09 14:43 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/reportHistory.cy.js
> +describe('Incidents', () => {
Fixed

2023-08-11 17:54 UTC, cesarvarela commented
@pdcp1 where is the reports history visible?

2023-08-11 18:42 UTC, pdcp1 commented
> where is the reports history visible?

@cesarvarela Good question lol. I forgot to add the location here.
The buttons are part of the Report action toolbar:

1. On the report card
<img width="1177" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/33db99f6-2697-4bb7-8a34-d1ef5ed7964d">

1. On the discovery report card
<img width="329" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/4914da54-60c3-4e3e-a85c-153adc161f53">

2023-08-14 18:00 UTC, cesarvarela reviewed
Not sure if related but I'm getting an error when trying to save changes to a report:

https://deploy-preview-2221--staging-aiid.netlify.app/cite/edit/?report_number=3193&incident_id=559

<img width="1126" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/59e0670f-099b-4efe-9750-fd2212dc9019">

2023-08-16 14:48 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/integration/reportHistory.cy.js
> +  const url = '/cite/history?report_number=3206&incident_id=563';
We need the `incident_id` to format the `Back to Report` button URL. This works in the same way as the Report Edit page. If we don't pass the `incident_id` param in the querystring, we have to d a query on the `incidents` collection to know that value.

2023-08-16 16:03 UTC, pdcp1 commented
@cesarvarela 
> Not sure if related but I'm getting an error when trying to save changes to a report:
> 
> https://deploy-preview-2221--staging-aiid.netlify.app/cite/edit/?report_number=3193&incident_id=559

This is happening on Staging as well 😕
https://staging-aiid.netlify.app/cite/edit/?report_number=3193&incident_id=559

I created an [issue](https://github.com/responsible-ai-collaborative/aiid/issues/2237) to fix as high priority

2023-08-17 23:07 UTC, pdcp1 commented on site/gatsby-site/src/pages/cite/history.js
> +  }, []);
Yes, use the `fetchPolicy: 'network-only'` is better.
I removed the `useEffect` function and add the `fetchPolicy: 'network-only'` to the `useQuery`

2023-08-18 21:42 UTC, cesarvarela requested changes
I made some edits and then when trying to fetch the Report's history page, It crashed:

<img width="1223" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/db106ad2-c4f1-4410-a89c-cfdf3b3fa237">

https://deploy-preview-2221--staging-aiid.netlify.app/cite/history/?report_number=3197&incident_id=561

2023-08-19 01:03 UTC, pdcp1 commented
> I made some edits and then when trying to fetch the Report's history page, It crashed:

This will be fixed after merging this [PR](https://github.com/responsible-ai-collaborative/aiid/pull/2245) that runs a migration.

2023-08-21 16:37 UTC, cesarvarela approved these changes

2023-08-21 16:37 UTC, merged