Feature/prismic docs
responsible-ai-collaborative/aiid pull request #2287
Opened 2023-09-14 13:52 UTC by clari182

- Part of https://github.com/responsible-ai-collaborative/aiid/issues/2048

Allows docs to be created via Prismic.
Docs are essentially pages, like about, contact & follow etc

This fetches docs from prismic and available doc mdx files present. It will only create MDX pages with available slugs.
For example if the contact page is in Prismic with slug `/contact` and an MDX file exists with slug `/contact` it will only use the prismic one.

2023-10-16 19:45 UTC, pdcp1 requested changes
The code looks good. The only thing that I think is missing is the test of this new feature.

2023-10-23 17:05 UTC, pdcp1 approved these changes

2023-10-27 00:47 UTC, cesarvarela approved these changes

2023-11-07 13:22 UTC, clari182 commented
@cesarvarela can we merge this?

2023-11-16 19:01 UTC, merged