Checklisting – add authentication
responsible-ai-collaborative/aiid pull request #2333
Opened 2023-10-04 00:49 UTC by lmcnulty

Resolves #2300.

2023-10-12 21:34 UTC, pdcp1 requested changes
Please add some tests for all possible cases (ie: authenticated as owner, authenticated as not the owner, unauthenticated)

2023-10-12 21:34 UTC, pdcp1 commented on site/gatsby-site/src/pages/apps/checklists.js
> +          } */
We should delete this commented code if it's not needed

2023-10-12 21:34 UTC, pdcp1 commented on site/gatsby-site/src/graphql/checklists.js
> +
I didn't find where is this mutation being used. Please delete this declaration statement if it's not used.

2023-10-17 18:41 UTC, pdcp1 commented
@lmcnulty do you know why the build is failing? It should pass before merge this.

2023-10-17 23:46 UTC, lmcnulty commented
@pdcp1 It's building now, I had to update a line a rebuild after a test flake.

2023-10-18 16:59 UTC, pdcp1 commented
Last successful build https://app.netlify.com/sites/staging-aiid/deploys/652f08291989fd0d0d00da13

2023-10-18 17:02 UTC, pdcp1 approved these changes

2023-10-19 21:54 UTC, merged