Support JA locale
responsible-ai-collaborative/aiid pull request #2439
Opened 2023-11-29 02:50 UTC by technohippy

I'm adding resources for JA locale.

2023-11-30 17:39 UTC, kepae commented
Hey @technohippy -- thanks for the PR, this is great! Would love to help Japanese readers.

Feel free to let us know when this is ready to be reviewed so that we can deploy a preview of the changes on Netlify.
(I note that some changed files are not entirely translated, [e.g.](https://github.com/responsible-ai-collaborative/aiid/blob/e60122a73be53a88b072c3efbb0328b68a991e02/site/gatsby-site/i18n/locales/ja/submit.json))

2023-12-06 07:53 UTC, technohippy commented
@kepae Translation's been done. Could you review this PR?

2023-12-06 17:45 UTC, kepae commented
I reviewed the content (with a ~little~ lot of help from DeepL and Google Translate).

However, the deploy I enabled failed due to tests not passing, and then exceeding the Netlify build limit due to time needed to retry tests:
https://app.netlify.com/sites/staging-aiid/deploys/65701f3345af4700084f5fee

```
10:43:28 AM:   1) Edit report
10:43:28 AM:        Should load and update report values:
10:43:28 AM:      TypeError: The following error originated from your application code, not from Cypress.
10:43:28 AM:   > Cannot read properties of undefined (reading "title")
10:43:28 AM: When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
10:43:28 AM: This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
10:43:28 AM: https://on.cypress.io/uncaught-exception-from-application
10:43:28 AM:       at <unknown> (http://localhost:8080/component---src-pages-cite-edit-js-445fcac5ccff4fc2c127.js:1:41888)
10:43:28 AM:       at Array.map (<anonymous>)
10:43:28 AM:       at C (http://localhost:8080/component---src-pages-cite-edit-js-445fcac5ccff4fc2c127.js:1:41457)
10:43:28 AM:       at Eo (http://localhost:8080/framework-6858c50a67608e0b80d0.js:2:63758)
```

I'll sync to this PR and see if I can debug/run tests locally. There may be some other configurations for the locale data, and if so, we should think about simplifying and documenting!

2023-12-07 01:07 UTC, technohippy commented
Sorry, some other files may have to be modified. I added some fixes but they must not enough.

2023-12-07 02:46 UTC, technohippy commented
I'll try to fix these issues this weekends.

2023-12-11 01:43 UTC, technohippy commented
@kepae I don't have cypress account but AIID in ja seems run successfully on my laptop anyway.

2023-12-11 22:22 UTC, kepae requested changes
Thanks for updating all of these various pieces, this PR will help make documentation on contributing language support.

For now, tests are still failing, and I can look into them repoducing them locally.
For running tests, a cypress cloud account isn't necessary -- any test can be run locally as well!

2023-12-12 02:39 UTC, technohippy commented
Thank you for running tests for me. Yes, I can run tests on my laptop but they throw a lot of 401 errors so I gave up to run tests. I'll investigate more. Anyway I fixed a url and applied your change.

2024-01-09 17:54 UTC, kepae reviewed
Circling back here with new 2024 energy -- hope you've had a good year so far @technohippy !

We have since implemented a github workflow to build + test changes and in parallel deploy them (not blocking on tests), and are working on making this easier for contributors.

Until that's perfected -- @pdcp1 would you please take a look at these changes and see if you can build+test this locally? and provide any guidance on the translation changes?

2024-01-09 18:00 UTC, pdcp1 commented
Sure, I will take a look

2024-01-12 21:40 UTC, pdcp1 commented
@technohippy Could you please merge `staging` branch into this one to pull the last changes? We made some improvements on the tests and deployment.
In the meantime, I am performing tests to determine the reason for the failed tests and will update you soon.

2024-01-17 16:56 UTC, pdcp1 requested changes

2024-01-18 23:35 UTC, technohippy commented
@pdcp1 Thansk, I'll fix them all this weekends.

2024-01-19 14:55 UTC, technohippy commented on site/gatsby-site/cypress/e2e/integration/citeEdit.cy.js
> +          'Este es el texto que tiene un largo mayor a ochenta caracteres en frances!'
done

2024-01-19 14:55 UTC, technohippy commented on site/gatsby-site/cypress/e2e/integration/citeEdit.cy.js
> +          'Este es el texto que tiene un largo mayor a ochenta caracteres en frances!\n'
done

2024-01-19 14:56 UTC, technohippy commented on site/gatsby-site/cypress/e2e/unit/pageCreators/createReportPages.cy.js
> +  },
done

2024-01-19 14:56 UTC, technohippy commented on site/gatsby-site/cypress/e2e/unit/pageCreators/createCitationPages.cy.js
> +  },
done

2024-01-23 00:09 UTC, pdcp1 requested changes
A new translation file `/gatsby-site/i18n/locales/en/incidents.json` was added to the project. Please copy that file into the `/gatsby-site/i18n/locales/ja` folder.
If your fork is not up to date you should merge Staging again.

2024-01-25 15:01 UTC, closed without merging