Remove subscriptions duplicate - migration
responsible-ai-collaborative/aiid pull request #2441
Opened 2023-11-29 16:11 UTC by clari182

Migration that removes duplicates in subscriptions collection

2023-12-05 21:10 UTC, pdcp1 commented
@clari182 Did you count the unique `notifications` and `subscriptions` on Production?
I just queried all `processed: false` notifications on Production and got 94 items (with duplicates).

I'm worried about the email burst when we activate the notifications process back 🤔 
@kepae What do you think? Should we delete all pending notifications (`processed: false`) and start from scratch?

2023-12-06 15:09 UTC, clari182 commented
IMO it would be best to start from scratch and set those manually to true. Because looking at it, they are duplicated notifications, so the emails were already sent in the past.

@pdcp1 I have the list of _id of the duplicated `subscriptions`

2023-12-07 15:49 UTC, kepae commented
>> I'm worried about the email burst when we activate the notifications process back 🤔
@kepae What do you think? Should we delete all pending notifications (processed: false) and start from scratch?
>
> IMO it would be best to start from scratch and set those manually to true. Because looking at it, they are duplicated notifications, so the emails were already sent in the past.

We should:
1. De-duplicate subscriptions in this migration.
1. Start notifications from scratch again, e.g. flip all pending (`processed: false`) notifications.
1. Closely monitor notification queues and subscriptions in the following builds (while working on https://github.com/responsible-ai-collaborative/aiid/issues/2473).

2023-12-08 12:41 UTC, clari182 commented
@pdcp1 Fixed the migration! Ready for another look

2023-12-11 21:43 UTC, kepae approved these changes

2023-12-11 23:59 UTC, cesarvarela approved these changes
Running this on one's "mind server" is challenging, so if you guys already tested it, go for it; otherwise, if you are not confident, a couple of tests wouldn't hurt.

2023-12-12 00:04 UTC, kepae commented
I agree, particularly because we don't backup user subscriptions currently (as mentioned on Slack).

(Aside: we should re-assess how to do full DB backups including subscriptions and other custom data.)

2023-12-12 20:34 UTC, pdcp1 requested changes

2023-12-12 20:34 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/unit/migrations/2023.11.29T14.56.25.delete-duplicated-subscriptions.cy.js
> +          uniqueIds: ['5f9f6b9b5f9c4c0001a3b3a5', '5f9f6b9b5f9c4c0001a3b3a6'],
We should use the same type `ObjectID` to keep consistency.

2023-12-12 20:34 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/unit/migrations/2023.11.29T14.56.25.delete-duplicated-subscriptions.cy.js
> +          uniqueIds: ['5f9f6b9b5f9c4c0001a3b3a7', '5f9f6b9b5f9c4c0001a3b3a8'],
The same here. We should use `ObjectID` type as well

2023-12-12 20:34 UTC, pdcp1 commented on site/gatsby-site/cypress/e2e/unit/migrations/2023.11.29T14.56.25.delete-duplicated-subscriptions.cy.js
> +        console.log(type);
Please remove all `console.log` statements since are not used in tests

2023-12-13 16:33 UTC, pdcp1 approved these changes
LGTM 👍

2023-12-15 18:41 UTC, kepae commented
Thanks for adding the test @clari182 . Let's merge and deploy this to production on Monday, along with:
* https://github.com/responsible-ai-collaborative/aiid/pull/2476

2023-12-18 17:31 UTC, merged