Fix/open graph - use gatsby head
responsible-ai-collaborative/aiid pull request #2573
Opened 2024-01-19 13:16 UTC by clari182

2024-01-19 16:26 UTC, clari182 commented
@cesarvarela please hold on review thanks!

2024-01-22 21:13 UTC, cesarvarela requested changes
Needs to remove `react-helmet` from `package.json`

Considering that we have talked in the past about removing specific references to AIID #1957, this might be a good opportunity to use a more generic name.

2024-01-22 21:13 UTC, cesarvarela commented on site/gatsby-site/src/components/AiidHead.js
> +      {children && <>{children}</>}
Why this change?

2024-01-23 12:13 UTC, clari182 commented on site/gatsby-site/cypress/e2e/integration/submit.cy.js
> +      cy.get(`input[name="${key}"]`).type(valuesStep1[key]);
Yes, the open graph `title`. Now that it exists there are 2 elements with the `title` name

2024-02-07 18:11 UTC, clari182 commented on site/gatsby-site/cypress/e2e/integration/submit.cy.js
> +      cy.get(`input[name="${key}"]`).type(valuesStep1[key]);
You're right, that was wrongly defined!

2024-02-23 18:06 UTC, cesarvarela commented on site/gatsby-site/src/components/AiidHead.js
> +  metaDescription = metaTitle,
This is a weird default. All pages should have a title and a description for SEO purposes besides just correctness.  If one of these is missing, it is okay if the build crashes.

2024-02-23 18:06 UTC, cesarvarela commented on site/gatsby-site/src/components/AiidHead.js
> +  title = null,
We should use either `title` or `metaTitle` but not both since they refer to the same thing.

2024-03-04 11:53 UTC, clari182 commented
@cesarvarela this is ready for review

2024-03-08 19:20 UTC, cesarvarela reviewed
Some open graph related test are failing, is it flake?

<img width="572" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/1172479/b0b361c4-009f-478c-a018-9ed47e9a6447">

2024-03-12 12:55 UTC, clari182 commented
Fixed @cesarvarela

2024-03-19 17:11 UTC, cesarvarela approved these changes

2024-03-19 18:16 UTC, kepae commented
Good to merge and test in staging @clari182 ?

2024-04-02 15:29 UTC, kepae commented
Please resolve conflicts and let me know when I can merge this. Sorry if the other PRs forced this out of sync.

2024-04-05 15:43 UTC, merged