Add migration and fix function to add created_at
responsible-ai-collaborative/aiid pull request #2612
Opened 2024-02-02 12:20 UTC by clari182

- closes #2611 

Before merging this to staging we need to pause the created_at triggers and do a DB restore from PROD to STAGING (because right now all entries on staging have false created_at values due to last restore).

Steps:

1. Disable `onNewEntry_customData`, `onNewEntry_history`, `onNewEntry_aiidprod` and `onNewEntry_translations` triggers.
2. Restore Staging DB from PROD - this will restore entries without `created_at`
3. Verify triggers are still disabled
4. Merge PR
5. Check if triggers are enabled (they should be automatically re-enable when merging the PR)

The collections `incidents`, `submissions` and `reports` should have correct values in `created_at`

### Default `created_at` values
- For `incidents` collection: Incident `date` field
- For `submissions` collection: Submission `date_submitted` field
- For `reports` collection: Report `date_submitted` field
- For `history.incidents` collection: Incident `date` field
- For `history.submissions` collection: Submission `date_submitted` field
- For `history.reports` collection: Report `date_submitted` field

2024-02-08 00:13 UTC, pdcp1 commented
@clari182 Is this ready for review? I saw a commit after you assigned it to me to review.

2024-02-08 12:17 UTC, clari182 commented
@pdcp1 yes! ready for review!

2024-02-14 20:15 UTC, pdcp1 requested changes
@clari182 I extracted the default value information from the code and added them to the PR description under `Default created_at values` section.
Please review and correct them if they are wrong.

2024-02-14 20:15 UTC, pdcp1 commented on site/gatsby-site/migrations/2024.02.01T20.03.56.set-incidents-submissions-reports-created_at.js
> +  // New created_at field on incidents and submissions collections
Please change the comment to include all 6 collections included in this migration

2024-02-14 20:55 UTC, pdcp1 approved these changes

2024-02-20 16:17 UTC, kepae commented
If I understand correctly, when _any_ PR gets merged to staging, all of the triggers will be activated again per the realm config that gets pushed. Should we pause all staging activity while doing this restore?

Walk me through this in standup, please. :-)

2024-02-22 12:56 UTC, clari182 commented
> If I understand correctly, when _any_ PR gets merged to staging, all of the triggers will be activated again per the realm config that gets pushed. Should we pause all staging activity while doing this restore?

If the triggers are inactive and there's a push to staging, the realm will pick up that those triggers should be active and reactivate them. Let me know when you think we should merge this.

2024-02-26 13:35 UTC, clari182 commented
@kepae @cesarvarela let me know when we're good to merge this

2024-02-26 15:07 UTC, kepae commented
Let's do this today, just merged your other PR (#2647). I'll disable the triggers in staging once that deploys.

2024-02-26 20:15 UTC, kepae commented
Disabled triggers in staging and ran the DB restore workflow:
https://github.com/responsible-ai-collaborative/aiid/actions/runs/8054935747/job/22000638557
(NB - it sends a build request to netlify still....)

Merging now.

2024-02-26 20:15 UTC, merged

2024-02-26 20:16 UTC, kepae commented
FYI: The `onIncidentUpdate` and `onNewIncident` triggers hit errors after restoring the DB (as usual). I restarted them before merging this PR.

2024-02-26 21:27 UTC, kepae commented
All triggers are re-enabled now, with recent runs:
<img width="1368" alt="Screenshot 2024-02-26 at 4 27 02 PM" src="https://github.com/responsible-ai-collaborative/aiid/assets/4238598/aa2a448e-3a90-4ce0-85db-de3c586fa3e6">

@clari182 over to you to check that new fields meet your expectations :-)