Feature/quiet submission
responsible-ai-collaborative/aiid pull request #2679
Opened 2024-03-05 15:07 UTC by clari182

2024-03-08 17:40 UTC, clari182 commented
@kepae @datherton09 the quiet option is ready for a test round. Let me know if you think it looks ok the way it does.
![image](https://github.com/responsible-ai-collaborative/aiid/assets/4105289/2f199cfb-bffc-45c7-a526-0e68ccb8ab03)

That option is on the submission form and report edit form

The test url is: https://pr-46--clarayoudale-staging.netlify.app/
Ping me for login credentials

2024-03-13 17:35 UTC, kepae requested changes
LGTM, just curious about how to best test this.

2024-03-13 17:35 UTC, kepae commented on site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js
is there a meaningful way to add a test case where `quiet: true`, and check that the expected report has the field propagated?

2024-03-15 14:15 UTC, clari182 commented on site/gatsby-site/cypress/e2e/unit/functions/promoteSubmissionToReport.cy.js
Updated a test to include the quiet field

2024-03-19 17:43 UTC, kepae approved these changes
Thanks for adding the test!

2024-04-01 17:30 UTC, kepae commented
@clari182 thanks for updating/syncing. :-) Good to merge to staging?

2024-04-01 18:52 UTC, clari182 commented
@kepae Yes we're good to merge!

2024-04-01 19:24 UTC, merged