Add next/previous incident buttons in cite header
responsible-ai-collaborative/aiid pull request #2689
Opened 2024-03-13 00:23 UTC by lmcnulty

First item of https://github.com/responsible-ai-collaborative/aiid/issues/2685.

Putting the links in the header to avoid taking up so much space.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/62801a57-c3a4-448d-b0ba-71caa92f1842)

2024-03-15 21:22 UTC, pdcp1 requested changes
In general, it looks good to me. I recommend adding tests to these buttons on `cite.cy.js`.
Please take into consideration this [edge-case scenario](https://github.com/responsible-ai-collaborative/aiid/issues/2695) for the first and last incident in the database.

FYI: I fixed it for the buttons at the bottom in this [PR](https://github.com/responsible-ai-collaborative/aiid/pull/2696)

2024-03-18 22:06 UTC, pdcp1 requested changes
Please add tests to these new buttons. You can copy the test structure from this [PR](https://github.com/responsible-ai-collaborative/aiid/pull/2696/files)

2024-04-02 23:19 UTC, pdcp1 approved these changes

2024-04-19 14:49 UTC, kepae commented
Sorry for the delay here. Could you please update this PR so it can be merged?

2024-04-24 23:33 UTC, pdcp1 approved these changes

2024-04-30 18:22 UTC, merged