Landing page incident title page creator
responsible-ai-collaborative/aiid pull request #2710
Opened 2024-03-27 03:26 UTC by lmcnulty

2024-03-27 03:26 UTC, lmcnulty commented on site/gatsby-site/gatsby-config.js
> +    DEV_SSR: false,
Don't include this.

2024-03-28 14:51 UTC, kepae requested changes
only one comment!

2024-03-28 14:51 UTC, kepae commented on site/gatsby-site/page-creators/createLandingPage.js
> +    query WordCounts {
please rename the query?

2024-03-29 16:02 UTC, lmcnulty commented on site/gatsby-site/page-creators/createLandingPage.js
> +    query WordCounts {
Good catch, thanks.

2024-03-29 16:29 UTC, kepae approved these changes

2024-03-29 18:46 UTC, merged