Add checklists to sidebar
responsible-ai-collaborative/aiid pull request #2752
Opened 2024-04-25 18:08 UTC by lmcnulty

The sidebar contents is actually controlled from Prismic now, so the change would need to be made there also.

2024-05-16 12:13 UTC, clari182 requested changes
Looks good! The only thing is missing is "Risk Checklists" translations. I've added the sidebar item to Prismic prod, once deployed we need to publish it.

2024-05-16 16:49 UTC, lmcnulty commented
I've added French and Spanish translations – I'm not sure what to do for the Japanese, though.

2024-05-17 18:15 UTC, kepae commented
Let's not block on Japanese. We can add tests later for tracking which languages have which strings completed for translations across files. Maybe we can actually add this as a leaderboard problem for contributors? :-) 

But in the meantime, let's ship risk checklists in staging and get ready for making in public!

2024-05-20 15:50 UTC, clari182 approved these changes

2024-05-21 16:32 UTC, merged