Add random incident option
responsible-ai-collaborative/aiid pull request #2767
Opened 2024-05-02 18:59 UTC by lmcnulty

Resolves https://github.com/responsible-ai-collaborative/aiid/issues/1577.

Adds a url, `/random/` which redirects to the citation page for a randomly-selected incident. I imagine this being linked in the sidebar – it needs to be set in Prismic.

2024-05-14 11:57 UTC, clari182 requested changes
Looks good! Just 2 japanese translations missing, and can you add some tests for this?

2024-05-14 11:57 UTC, clari182 commented on site/gatsby-site/i18n/locales/ja/translation.json
> +  "Random Incident": "Random Incident"
Please add Japanese translations

2024-05-14 13:54 UTC, kepae commented
Does this PR build? Errors on the test build pipeline: https://github.com/responsible-ai-collaborative/aiid/actions/runs/8929044728/job/24525956231?pr=2767

2024-05-15 16:31 UTC, lmcnulty commented on site/gatsby-site/i18n/locales/ja/translation.json
> +  "Random Incident": "Random Incident"
Attempted. For "redirecting..." I went with "リダイレクト中..." which got from Google translate and [seems to be used for this exact purpose](https://www.google.com/search?q=%22%E3%83%AA%E3%83%80%E3%82%A4%E3%83%AC%E3%82%AF%E3%83%88%E4%B8%AD...%22) in a lot of sites. Then for the random button I went with "おまかせ表示" which is taken verbatim from the random page link of Japanese Wikipedia.

2024-05-17 15:00 UTC, clari182 reviewed
This looks good!! Works as expected.
I've added the new item to the sidebar on staging and prod, when this PR is merged it will be visible on the sidebar in staging (and then prod).
Do you think it would be much work to add a button in the cite page to load another random incident?
If you know you're coming from a random incident, maybe the button would say something like "Display another random incident" (or maybe something shorter and better), so it re-triggers the `/random/` path

2024-05-17 16:51 UTC, lmcnulty commented
@clari182 I think a good way to handle this is putting a random incident link between the next and previous links on the cite page, as is often done in webcomics. Then there's no need to determine if we came from the random page.

![image](https://github.com/responsible-ai-collaborative/aiid/assets/25443411/e2299637-8b80-40b4-bbd4-24a53d5ea193)

2024-05-22 15:25 UTC, clari182 approved these changes

2024-05-22 18:43 UTC, merged