Checklists - fix section collapse on change query tags
responsible-ai-collaborative/aiid pull request #2777
Opened 2024-05-03 20:41 UTC by lmcnulty

Resolves https://github.com/responsible-ai-collaborative/aiid/issues/2706

2024-05-14 16:18 UTC, pdcp1 commented
@lmcnulty, can you please provide a description of the issue at https://github.com/responsible-ai-collaborative/aiid/issues/2706? 
I'm unable to test or review the code without understanding the problem. Thanks!

2024-05-14 22:27 UTC, lmcnulty commented
@pdcp1 The issue with what we have now is that changing the query of a risk causes it to collapse, because we check the open/closed status of a risk by its query. This changes it so that changing the query also changes the one used to represent the open/closed status.

https://github.com/responsible-ai-collaborative/aiid/assets/25443411/18a97033-21bb-44b0-bd6e-b3eae95df08e

2024-05-15 21:38 UTC, pdcp1 requested changes
The code looks good and the issue is fixed 👍 
Please add tests.

2024-05-17 22:14 UTC, pdcp1 approved these changes

2024-05-17 22:17 UTC, merged