Add right sidebar content for prismic content
responsible-ai-collaborative/aiid pull request #2795
Opened 2024-05-21 11:28 UTC by clari182

2024-05-21 19:12 UTC, cesarvarela commented on site/gatsby-site/src/components/blog/PrismicBlogPost.js
> +  useEffect(() => {
Can using an effect be avoided? Is it because of hydration errors?

2024-05-21 19:12 UTC, cesarvarela commented on site/gatsby-site/src/components/doc/PrismicDocPost.js
> +  useEffect(() => {
ditto

2024-06-03 16:40 UTC, clari182 commented
@cesarvarela ready for another review!

2024-08-28 18:41 UTC, cesarvarela requested changes
Sorry, I missed this review. 

Please migrate the test to Playwright.

2024-11-05 18:16 UTC, cesarvarela approved these changes

2024-11-05 18:17 UTC, merged