Display incidents instead of reports for similar/dissimilar incidents
responsible-ai-collaborative/aiid pull request #2815
Opened 2024-06-04 15:37 UTC by clari182

- closes #2799 
- Test URL: https://pr-2815--staging-aiid.netlify.app/
- Uses incident autocomplete input to search incident
- Displays one result per incident instead of all its reports

2024-06-05 17:24 UTC, clari182 commented
Hey @datherton09 , can you take a look at this PR and let me know if the new design for similar/dissimilar looks ok to you? 
The test URL is https://pr-2815--staging-aiid.netlify.app/
The changes are
- It only displays incidents instead of reports when searching by incident ID
- New tooltip with information on how to use that functionality
- Some minor design changes
Let me know what you think. Thanks!!
<img width="962" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/4105289/d96aaad3-3632-409a-9759-1385a5654c86">

2024-06-05 17:35 UTC, datherton09 commented
@clari182 Nice! Thanks :) Where is the tooltip located?

2024-06-06 12:24 UTC, clari182 commented
@datherton09 the tooltip is located right next to `Search similar incident ID`

2024-09-24 21:43 UTC, pdcp1 requested changes
Great UI improvements! 👏 

While playing with the UI, I found an issue after clicking the "Not sure" button. A multi-state is displaying. Please take a look at the attached video for a clear reference.



https://github.com/user-attachments/assets/101a8765-42e5-415b-aeda-188f03444d10

2024-09-24 21:43 UTC, pdcp1 commented on site/gatsby-site/i18n/locales/en/popovers.json
> +        "text": "Search for a similar or dissimilar incident by typing an incident ID. If the resulting incident is similar click 'Yes', if it's dissimilar click 'No'. If you're not sure click 'Not s
I can't find the usage of these `similarIncidentSearch` popover

2024-09-24 21:43 UTC, pdcp1 commented on site/gatsby-site/playwright/e2e-full/apps/incidents.spec.ts
> +    // TODO: Fix this
Is this `TODO:` still needed?

2024-09-24 21:43 UTC, pdcp1 commented on site/gatsby-site/src/components/incidents/IncidentForm.js
> +              'No similar/dissimilar incidents assigned to this incident. Use the search above to assign similar incidents.'
Translation missing

2024-09-24 21:43 UTC, pdcp1 commented on site/gatsby-site/src/components/incidents/IncidentForm.js
> +                  'No similar incidents found. Please enter an incident ID above to perform the search.'
Translation missing

2024-09-24 21:43 UTC, pdcp1 commented on site/gatsby-site/src/components/incidents/IncidentForm.js
> +                header={similarIncidentsById.length > 0 ? 'Incidents search results' : ''}
Translation missing

2024-09-26 17:19 UTC, pdcp1 approved these changes
It looks good to me now 👍

2024-09-27 15:47 UTC, cesarvarela commented
@clari182 please merge staging; everything should be ✅

2024-09-27 19:14 UTC, merged