Feature/playwright account
responsible-ai-collaborative/aiid pull request #2841
Opened 2024-06-12 18:52 UTC by clari182

- closes #2840

2024-07-02 20:57 UTC, cesarvarela requested changes
Please merge staging, playwright workflow should be green now.

2024-07-02 21:17 UTC, pdcp1 commented
Re-running checks since these 3 tests were skipped in the last run. These 3 tests should be executed now:

<img width="994" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/fa42cae5-db5a-471f-9092-59ede1eea3df">

2024-07-02 22:44 UTC, pdcp1 commented
> Re-running checks since these 3 tests were skipped in the last run. These 3 tests should be executed now:
> 
> <img alt="image" width="994" src="https://private-user-images.githubusercontent.com/6564809/345202616-fa42cae5-db5a-471f-9092-59ede1eea3df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjA0OTcsIm5iZiI6MTcxOTk2MDE5NywicGF0aCI6Ii82NTY0ODA5LzM0NTIwMjYxNi1mYTQyY2FlNS1kYjVhLTQ3MWYtOTA5Mi01OWVkZTFlZWEzZGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMjI0MzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDE5Yjk2OTFkZmE4OGFiZThmYjEwZjRhZDg2Mzg4N2QyNjI5Yjg5NzhjODgwZmNmMGQ0NDY1MjBkODk5ZjU3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5yvAcHFm7dlhctX7jx68KOb4bJBQMG90AaRB9bYCgEM">

They are still being skipped. @clari182 please merge staging and check if all Account tests pass

2024-07-03 23:24 UTC, pdcp1 requested changes
Some tests are failing
<img width="997" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/00b4fd08-1dba-474a-a74c-f698a98d08eb">

2024-07-11 18:24 UTC, pdcp1 requested changes

2024-07-11 18:24 UTC, pdcp1 commented on site/gatsby-site/session.json
Is this file needed for the account test file?

2024-07-11 18:44 UTC, pdcp1 approved these changes

2024-07-11 18:45 UTC, merged