Migrate dymanicCite.cy to playwright
responsible-ai-collaborative/aiid pull request #2896
Opened 2024-06-20 14:42 UTC by clari182

2024-06-22 00:44 UTC, pdcp1 requested changes
We should delete the original Cypress test file `cypress/e2e/integration/dynamicCite.cy.js`

2024-06-22 00:44 UTC, pdcp1 commented on site/gatsby-site/playwright/e2e/dynamicCite.spec.ts
> +  test('Should load dynamic Incident data', async ({ page, login }) => {
The original test has this condition `!Cypress.env('isEmptyEnvironment') && Cypress.env('e2eUsername') && Cypress.env('e2ePassword')` so I think the new one should have the `skipOnEmptyEnvironment`

2024-06-22 00:44 UTC, pdcp1 commented on site/gatsby-site/playwright/e2e/dynamicCite.spec.ts
> +  test('Should display a new Variant if live mode is turned on', async ({ page, login }) => {
The same here. I think the new one should have the `skipOnEmptyEnvironment`

2024-06-22 00:44 UTC, pdcp1 commented on site/gatsby-site/playwright/e2e/dynamicCite.spec.ts
> +  test('There should not be image errors (400)', async ({ page, login }) => {
idem, The original test has this condition `!Cypress.env('isEmptyEnvironment') && Cypress.env('e2eUsername') && Cypress.env('e2ePassword')` so I think the new one should have the `skipOnEmptyEnvironment`

2024-06-22 00:44 UTC, pdcp1 commented on site/gatsby-site/playwright/fixtures/incidents/incident10.json
I think we should delete the original fixture `cypress/fixtures/incidents/incident10.json` since it is only used in this test `dynamicCite` file. Please double check

2024-06-22 00:50 UTC, pdcp1 requested changes
I don't know why these 3 tests were skipped 🤔 
<img width="997" alt="image" src="https://github.com/responsible-ai-collaborative/aiid/assets/6564809/a37aa98f-d209-4c29-85f6-63711ca33f81">

2024-06-24 16:41 UTC, clari182 commented
Those 3 tests get skipped because of this error: `skip: E2E_ADMIN_USERNAME or E2E_ADMIN_PASSWORD not set`
It looks like those variables aren't set on the repo. cc @cesarvarela

2024-06-24 21:05 UTC, pdcp1 approved these changes

2024-06-24 21:06 UTC, merged