Prevent notification process from crashing if no recipients
responsible-ai-collaborative/aiid pull request #3301
Opened 2024-12-20 19:26 UTC by cesarvarela

2024-12-30 21:50 UTC, pdcp1 requested changes

2024-12-30 21:50 UTC, pdcp1 commented on site/gatsby-site/server/tests/notifications.spec.ts
> +    it('Should not crash if no recipients found', async () => {
It looks like this test is failing https://github.com/responsible-ai-collaborative/aiid/actions/runs/12437299433/job/34998005994?pr=3301

2025-01-20 20:14 UTC, cesarvarela commented on site/gatsby-site/server/tests/notifications.spec.ts
> +    it('Should not crash if no recipients found', async () => {
Fixed

2025-01-20 21:04 UTC, pdcp1 approved these changes

2025-01-20 21:05 UTC, merged