reworked sponsor block
responsible-ai-collaborative/aiid pull request #741
Opened 2022-06-28 06:24 UTC by smcgregor

fixes #561

2022-06-28 19:21 UTC, lmcnulty requested changes
See the inline comments. The only thing I'd say should definitely change is that there should be space between the text and the image in the modals. The subtitles for the sponsor logos also need attention, but it's a matter of taste what the appropriate choice is. Everything else is fairly unimportant.

2022-06-28 19:21 UTC, lmcnulty commented on site/gatsby-site/src/components/landing/Sponsors.js
> +            <Card.Body>
Having another `<Card.Body>` here makes the text not aligned with the header / cards above.

<img width="300" src="https://user-images.githubusercontent.com/25443411/176262703-3de5f7dd-991d-4207-a7c6-4ebb926980d5.png"/>

If you didn't intend for that to be the case, you could keep the gap between the columns by adding margin-left to the right `<Col>` when it's wide enough to not wrap.

2022-06-29 21:57 UTC, smcgregor commented on site/gatsby-site/src/components/landing/Sponsors.js
> +          imagePath={'/netlify-dark.svg'}
Updated locally, will push shortly.

2022-06-29 22:51 UTC, smcgregor commented on site/gatsby-site/src/components/landing/Sponsors.js
> +              <StyledSubtitle top={'0px'} margin={'0px'}>
Centered.

2022-06-29 23:06 UTC, merged