Classification column filters
responsible-ai-collaborative/aiid pull request #788
Opened 2022-07-12 14:59 UTC by lmcnulty

Resolves #739. A few items still have commas, but that's because they're incorrectly stored in MongoDB as strings. They should be replaced with arrays.

![image](https://user-images.githubusercontent.com/25443411/178519905-50c845f9-2383-4a18-8938-70ad1f54301e.png)

2022-07-26 16:53 UTC, cesarvarela commented
Is there an issue for the database side of things? Looks like this is half of the solution?

2022-08-15 18:33 UTC, cesarvarela commented
@lmcnulty, don't forget about my comment above; it looks like this doesn't completely close the issue?

2022-08-16 16:02 UTC, lmcnulty commented
@cesarvarela I've added a migration to fix the database issues.

<img src="https://user-images.githubusercontent.com/25443411/184925558-e3aaebf2-d44d-4c68-b54b-614622844e7c.png" width="600"/>

I'm wondering whether the "Location" field of the CSET taxonomy should be an array or a string? Right now it's a string, but some of the values seem to want to be arrays, e.g. `"Buenos Aires, Argentina, CONARC, Consulta Nacional de Rebeldías y Capturas."` If it becomes an array, though, should it be `["Buenos Aires, Argentina", …]`, `["Buenos Aires", "Argentina"…]`, or `["Buenos Aires, Argentina", "Argentina"…]`?

2022-08-16 16:25 UTC, smcgregor commented
`Buenos Aires, Argentina, CONARC, Consulta Nacional de Rebeldías y Capturas.` is a single location. If it is broken into an array, it would be treated as multiple locations and (for example) Buenos Aires and Argentina would be separately geocoded.

2022-08-16 18:57 UTC, cesarvarela requested changes
@lmcnulty That migration is tricky to follow, can you generate a log of all the updates it does (maybe by adding  a console log above each update) and share the log here?

2022-08-16 18:57 UTC, cesarvarela commented on site/gatsby-site/migrations/2022.08.15T19.33.01.remove-commas-in-classifications.js
> +        ![
Can you do the opposite here, so we are sure it is only updating what we want? 

Don't know how it is called, but "positive" filters are safer.

2022-08-17 14:11 UTC, lmcnulty commented
I've added logging to the migration. Here's the result:

```c
#2 Laws Implicated : [ 'Workplace safety laws; OSHA regulations' ] → [ 'Workplace safety laws', 'OSHA regulations' ]
#3 Laws Implicated : [
  'Federal Aviation Administration regulations; Indonesian air safety regulations'
] → [
  'Federal Aviation Administration regulations',
  'Indonesian air safety regulations'
]
#5 Data Inputs : [ "Surgeon's directions, medical procedures" ] → [ "Surgeon's directions", 'medical procedures' ]
#9 Data Inputs : [ 'School grades, student grades, predicted grades' ] → [ 'School grades', 'student grades', 'predicted grades' ]
#9 AI Applications : [ 'data processing, data prediction' ] → [ 'data processing', 'data prediction' ]
#45 Laws Implicated : [
  'Law of defamation in Australia, EU Electronic Commerce Directive,  judgment of Ribeiro PJ in Oriental Press Group Ltd & anor v Fevaworks Solutions Ltd [2013] 5 HKC 253 in Hong Kong'
] → [
  'Law of defamation in Australia',
  'EU Electronic Commerce Directive',
  'judgment of Ribeiro PJ in Oriental Press Group Ltd & anor v Fevaworks Solutions Ltd [2013] 5 HKC 253 in Hong Kong'
]
#49 Named Entities : [ 'Youth Laboratories, Microsoft' ] → [ 'Youth Laboratories', 'Microsoft' ]
#53 Data Inputs : [ 'user input, images' ] → [ 'user input', 'images' ]
#53 AI Techniques : [ 'open-source, machine learning' ] → [ 'open-source', 'machine learning' ]
#71 Laws Implicated : [
  'California Vehicle Code Section 38750; California DMV Autonomous Vehicle Testing Regulations'
] → [
  'California Vehicle Code Section 38750',
  'California DMV Autonomous Vehicle Testing Regulations'
]
#76 Data Inputs : [
  'photo IDs',
  'names',
  'birthdays',
  'and national IDs of people suspected of crimes;camera feed'
] → [
  'photo IDs, names birthdays, and national IDs of people suspected of crimes',
  'camera feed'
]
#82 Named Entities : [ 'Facebook, #EndSARS, Nigerian Army, Nigeria' ] → [ 'Facebook', '#EndSARS', 'Nigerian Army', 'Nigeria' ]
#88 Named Entities : [ 'Google Images, Google, raid' ] → [ 'Google Images', 'Google', 'raid' ]
#88 Data Inputs : [ 'images, tags, appended texts, user input' ] → [ 'images', 'tags', 'appended texts', 'user input' ]
#89 Named Entities : [ 'New Zealand, YouTube' ] → [ 'New Zealand', 'YouTube' ]
#89 Data Inputs : [ 'user history, videos' ] → [ 'user history', 'videos' ]
#92 Named Entities : [
  'Goldman Sachs, Apple Card, Apple, Steve Wozniak, New York Department of Financial Services'
] → [
  'Goldman Sachs',
  'Apple Card',
  'Apple',
  'Steve Wozniak',
  'New York Department of Financial Services'
]
#92 Data Inputs : [ 'credit score, credit report, reported income' ] → [ 'credit score', 'credit report', 'reported income' ]
#92 AI Techniques : [ 'machine learning, daya analytics' ] → [ 'machine learning', 'daya analytics' ]
#94 Harm Distribution Basis : [ 'Other:Those with emegencies, illness, unexpected circumstances' ] → [
  'Other:Those with emegencies',
  'illness',
  'unexpected circumstances'
]
```

2022-08-18 18:41 UTC, cesarvarela commented
@smcgregor can you validate that log above please?

2022-08-18 18:45 UTC, smcgregor commented
Log looks good to me. 👍

2022-08-18 18:50 UTC, cesarvarela approved these changes

2022-08-18 18:52 UTC, merged