Feature/tailwind blog listing
responsible-ai-collaborative/aiid pull request #825
Opened 2022-07-19 21:36 UTC by clari182

2022-08-04 19:54 UTC, cesarvarela commented
Please fix conflicts

2022-08-08 13:54 UTC, clari182 commented
@cesarvarela conflicts fixed

2022-08-09 18:37 UTC, cesarvarela approved these changes
Looks good should be merged after #822

2022-08-11 19:41 UTC, cesarvarela requested changes
There is a weird margin on the blog listing:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/1172479/184225007-163ca745-dc7a-4fa8-9d5d-5f7fc16ca644.png">


The links are black:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1172479/184225190-de558b02-1cf8-474a-b54f-66f1869ad25c.png">

2022-08-11 22:40 UTC, cesarvarela commented
please fix conflicts

2022-08-12 17:24 UTC, cesarvarela approved these changes

2022-08-12 17:33 UTC, cesarvarela requested changes
There is one text missing translations

2022-08-12 17:33 UTC, cesarvarela commented on site/gatsby-site/src/components/blog/PostPreview.js
> +          {post.excerpt}... <LocalizedLink to={post.frontmatter.slug}>(Read More)</LocalizedLink>
Missing `Trans`

2022-08-12 19:15 UTC, clari182 commented
@cesarvarela missing translation added, margins and links fixed

2022-08-12 19:27 UTC, cesarvarela approved these changes

2022-08-12 19:28 UTC, merged