Feature/tailwind landing page
responsible-ai-collaborative/aiid pull request #862
Opened 2022-07-26 18:03 UTC by clari182

2022-08-09 18:43 UTC, cesarvarela requested changes
there is a weird margin/padding here: 

![image](https://user-images.githubusercontent.com/1172479/183736843-315ac4a0-49be-4fe7-8d54-3e4eb5fe5345.png)

2022-08-10 22:08 UTC, clari182 commented
@cesarvarela fixed padding issues

2022-08-12 19:29 UTC, cesarvarela commented
Conflicts again 💥

2022-08-15 17:09 UTC, clari182 commented
@cesarvarela conflicts resolved!

2022-08-15 17:58 UTC, cesarvarela requested changes
something going on:

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/1172479/184689609-fa91c6c7-4811-420e-a37a-8dac701dbb30.png">

2022-08-17 22:11 UTC, cesarvarela approved these changes

2022-08-17 22:31 UTC, cesarvarela requested changes
The thing with the absolute position of the placeholder was to prevent the "search reports" text from flashing when loading the page. 

Maybe leaving it empty is an option 🤷

2022-08-17 22:31 UTC, cesarvarela commented on site/gatsby-site/src/components/landing/QuickSearch.js
> +  const [searchPlaceholder, setSearchPlaceholder] = useState('Search reports');
Can you leve this empty?

2022-08-18 18:38 UTC, cesarvarela commented
woot conflicts

2022-08-18 22:16 UTC, cesarvarela approved these changes

2022-08-18 22:16 UTC, merged