Social Share Buttons
responsible-ai-collaborative/aiid pull request #885
Opened 2022-08-01 21:01 UTC by pdcp1

This PR adds a new component `SocialShareButtons`

2022-08-04 22:34 UTC, cesarvarela commented
Should I get something elese than this?
<img width="662" alt="image" src="https://user-images.githubusercontent.com/1172479/182964082-e91dde98-0d74-4819-8aff-3f6178ff42e7.png">

seems to be missing the open graph stuff?

2022-08-04 22:38 UTC, pdcp1 commented
@cesarvarela I'm not sure if the openGraph improvements are already merged to Production. That's why the share preview in your case is not working.

2022-08-04 22:42 UTC, cesarvarela commented
Looks like it is working for fb
<img width="692" alt="image" src="https://user-images.githubusercontent.com/1172479/182965197-e84a74c1-5bcb-4722-8083-d8b8c313e469.png">

2022-08-04 22:43 UTC, cesarvarela commented
yes the open graph improvements are live

2022-08-05 18:29 UTC, cesarvarela commented
please fix conflicts!

2022-08-05 18:56 UTC, pdcp1 commented
Conflicts resolved!

2022-08-05 20:20 UTC, cesarvarela commented
The twitter test is failing

2022-08-05 23:33 UTC, pdcp1 commented
Twitter test fixed

2022-08-09 18:25 UTC, cesarvarela requested changes
Looks goods, but it is missing translations.

2022-08-10 00:42 UTC, pdcp1 commented
@cesarvarela Translations added

2022-08-11 19:30 UTC, cesarvarela requested changes

2022-08-11 19:30 UTC, cesarvarela commented on site/gatsby-site/src/components/submissions/SubmissionReview.js
> +              {isNewIncident ? <>Add New Incident</> : <>Add New Report</>}
Missing `Trans`

2022-08-11 19:30 UTC, cesarvarela commented on site/gatsby-site/src/components/submissions/SubmissionReview.js
> +              {isNewIncident ? <>Reject New Incident</> : <>Reject New Report</>}
ditto

2022-08-11 19:30 UTC, cesarvarela commented on site/gatsby-site/src/components/ui/SocialShareButtons.js
> +          title="Share by email"
ditto

2022-08-11 19:30 UTC, cesarvarela commented on site/gatsby-site/src/components/ui/SocialShareButtons.js
> +          title="Share to Facebook"
ditto

2022-08-15 18:30 UTC, cesarvarela approved these changes

2022-08-15 18:30 UTC, merged