Make set id and set similarity options only show when appropriate
responsible-ai-collaborative/aiid pull request #894
Opened 2022-08-03 19:19 UTC by lmcnulty

Addresses #868. Makes each of the the related incident views appear under the corresponding form field. Also removes the option to set similarity based on the URL or ID, as those will identify the same incident, not similar ones, which could be confusing.

![image](https://user-images.githubusercontent.com/25443411/182690859-50dace84-8892-4df5-9f68-bb27220b2c84.png)

2022-08-04 15:06 UTC, smcgregor commented
I think it would be better to display the incident title and potentially description here, rather than the complete list of reports. Some reports do not have informative titles, whereas we decide the incident titles.

2022-08-08 15:45 UTC, lmcnulty commented
The `RelatedIncidentsArea` can now display reports or incidents. Incidents are displayed under the incident id field and the text field:

![image](https://user-images.githubusercontent.com/25443411/183457061-31325d61-d78f-427f-8c41-fb8d35436dbe.png)

---

![image](https://user-images.githubusercontent.com/25443411/183456959-b4db5e0d-18e8-4eb5-bc6e-6d44462a3ead.png)

Whereas for the fields that are attributes of the report (author, date published, and url) we still display the reports instea:

![image](https://user-images.githubusercontent.com/25443411/183457673-d9a10f18-0116-4bd8-872e-e0dfcdbfb875.png)

2022-08-09 18:31 UTC, cesarvarela requested changes
Looks good but it is missing translations

2022-08-18 17:44 UTC, cesarvarela requested changes
Next time please create the i18n keys in the appropriate json and we'll comment with the translations there, so it is faster than me having to search for each <Trans> component 🍷

2022-08-18 17:44 UTC, cesarvarela commented on site/gatsby-site/src/components/RelatedIncidents.js
> +        <Trans>Incidents reports matched by published date:</Trans> <b>{incident.date_published}</b>
Informes de incidentes por fecha de publicación:

(this should be only one trans component that includes the `b` tags)

2022-08-18 17:44 UTC, cesarvarela commented on site/gatsby-site/src/components/RelatedIncidents.js
> +        <Trans>Incident matched by ID:</Trans> <b>{incident.incident_id}</b>
Incidentes por ID:

(this one needs to be in one Trans component too.)

2022-08-18 17:44 UTC, cesarvarela commented on site/gatsby-site/src/components/RelatedIncidents.js
> +        <Trans>Incidents reports matched by authors:</Trans> <b>{incident.authors}</b>
Informes por autor:

(ditto)

2022-08-18 17:44 UTC, cesarvarela commented on site/gatsby-site/src/components/RelatedIncidents.js
> +        <Trans>Incidents reports matched by URL:</Trans> <b>{incident.url}</b>
Informes por URL

(ditto)

2022-08-18 17:51 UTC, lmcnulty commented
Sorry about the missing keys – I would have added them but thought we had decided not to do that on account of a future system to detect missing translations automatically.

2022-08-18 18:36 UTC, cesarvarela commented
Yea, I think I miscommunicated that, once French is added we'll have to look into the automated thing, but for now just create the empty JSONs and just ping either Clara, Pablo or me, and we'll give the translated text.

2022-08-18 19:59 UTC, cesarvarela approved these changes

2022-08-18 20:00 UTC, merged