Create a placeholder page for each entity
responsible-ai-collaborative/aiid pull request #985
Opened 2022-08-19 22:43 UTC by cesarvarela

2022-09-12 18:21 UTC, cesarvarela commented
@smcgregor this is ready for another review

- added Common Entities card to landing page
- clickable harmed parties on citation pages
- small fixes

2022-09-19 19:49 UTC, pdcp1 commented
@cesarvarela This is more of a design comment, but maybe it's better to have the `Learn More` buttons aligned at the bottom of the card. A possible solution could be to have a fixed Card height.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/6564809/191103043-52a743d1-7732-4248-b66e-ceb413eba25b.png">

2022-09-19 21:11 UTC, pdcp1 requested changes

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +                            <Trans>View ({{ hidden }}) more</Trans>
Add missing translation, these two are not working in Spanish

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +                                    Incident {incident.incident_id}
Add missing translation

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +                                    {incident.reports.length} Reports(s)
Add missing translation

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/templates/entity.js
> +                      <h5 className="mt-6">{section.header}</h5>
Add missing translation

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/components/entities/AllegedEntities.js
> +      </Trans>
This translation is not working. Is it missing on the translation files?

2022-09-19 21:11 UTC, pdcp1 commented on site/gatsby-site/src/components/entities/AllegedEntities.js
> +    </Trans>
This translation is not working. Is it missing from the translation files?

2022-09-20 20:29 UTC, cesarvarela commented
Lol looks like halfway through, I decided translations were not worth any more xd, fixed.

I'm unsure what to do about the cards; both options will look weird; I could add a "read more" button to make the descriptions have the same length, but I wouldn't say I like it much.

2022-09-20 22:00 UTC, cesarvarela commented
@smcgregor please give it another look, it is almost ready to merge to staging

2022-09-20 22:37 UTC, pdcp1 approved these changes

2022-09-21 17:11 UTC, merged